name: UsingSecretsDemo

on:
  push:
    branches: ["main"]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use secret in environment
        env:
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: |
          echo "Using secret in environment"
          echo "SECRET_KEY is $SECRET_KEY"
